### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by Muvkina** [eudaldgr/kiss-live#1]
I'm aware you stated one of the goals is to slim this down. However I think it would be beneficial for this to have cryptsetup included with a kernel config for luks.

**Comment by eudaldgr** [comment]
I plan to make a custom config for kernel, PR are welcome!

**Comment by Muvkina** [comment]
Will do when I have the time.

**Comment by eudaldgr** [comment]
The current [config](https://github.com/eudaldgr/kiss-live/blob/master/repo/linux/files/config) have support for encryption.
