### ISSUE TITLE
wifi not working / firmware missing

### ISSUE THREAD

**Issue by ucodelukas** [eudaldgr/kiss-live#10]
I booted the kiss-live on my Laptop, good work ;)

but i cant use my wifi since its probably not enabled in kernel 

i work on a modified kernel and i got the firmware build files from somewhere , my goal is both working so that most hardware is working 

[linux-xanmod-and-kernel-firmware.zip](https://github.com/eudaldgr/kiss-live/files/5646593/linux-xanmod-and-kernel-firmware.zip)

**Comment by eudaldgr** [comment]
This is intended behavior, wifi modules are inside the livecd but you need to load properly and know which of them to use, there is no device manager to handle this procedure automatically.
- EDIT:
I see what you want, but propietary firmware blobs are not included by default, you can always run the script to build your own image like this: `sls kiss-live -p linux-firmware`
- EDIT 2:
I'm happy with my kernel config, I think it covers almost all possible needs. If you want to add some modules you can PR it, but your package are completely diferent, and the patches dir have files that doesn't apply inside the build script.
Clone the repo, remove my linux package, put yours and run the script if you want this, but i think xanmod it's thinked for DE, and this livecd have no DE included at all.

**Comment by ucodelukas** [comment]
i see and respect that
