### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by pinkyplant** [eudaldgr/kiss-live#11]
Hey, this is a really cool project but would you be able to update it with the newest tarball or even create a GH action to automate it? Thanks man.

**Comment by pinkyplant** [comment]
@eudaldgr

**Comment by eudaldgr** [comment]
KISSLinux is discontinued, there's something like a community driven fork, but i don't use it. Feel free to fork the project and update it. I close this, because is not an issue, and i don't respond to demands or requests.
