### ISSUE TITLE
Fails to copy chain.c32 when creating iso file

### ISSUE THREAD

**Issue by josephreynolds1** [eudaldgr/kiss-live#3]
Fails to copy chain.c32 when creating iso file

**make_iso
print 'Preparing isolinux files'
printf '%b \033[1;34m%s\033[m\n' '\033[1;33m->\033[m' 'Preparing isolinux files'
Preparing isolinux files
mkdir -p /tmp/kiss-live/iso/kiss
mkdir -p /tmp/kiss-live/iso/isolinux
mkdir -p /tmp/kiss-live/iso/boot
cp /tmp/kiss-live/files/isolinux.cfg /tmp/kiss-live/iso/isolinux
cp /usr/lib/syslinux/chain.c32 /tmp/kiss-live/iso/isolinux
cp: can't stat '/usr/lib/syslinux/chain.c32': No such file or directory**

**Comment by eudaldgr** [comment]
On [README](https://github.com/eudaldgr/kiss-live/blob/master/README), i say that you need to have some dependencies installed on your pc, they are packaged for KISS inside [repo folder](https://github.com/eudaldgr/kiss-live/tree/master/repo).
I don't offer support for different distros.

**Comment by eudaldgr** [comment]
Script now checks if depends are installed. [`1f44c21`](https://github.com/eudaldgr/kiss-live/commit/1f44c21faa775e474d55bcc39d6f10df413287ca)
