### ISSUE TITLE
"!! grub not installed" despite having all GRUB packages installed

### ISSUE THREAD

**Issue by aviumcaravan** [eudaldgr/kiss-live#4]
hi, i'm using a Fedora 32 system. despite installing all dependencies, i still get the "**!! grub not installed**" error. any idea how could i resolve this?

**Comment by eudaldgr** [comment]
The function to check dependency missing uses the paths where kiss package manager installs packages, so this will never work under other distros, you can try to remove this checks.

**Comment by eudaldgr** [comment]
~~Hint: remove function on [line 46](https://github.com/eudaldgr/kiss-live/blob/c9c1260510e25cbcb09326be1137e05a06d93dd8/kiss-live#L46) and this [line](https://github.com/eudaldgr/kiss-live/blob/c9c1260510e25cbcb09326be1137e05a06d93dd8/kiss-live#L289)~~

**Comment by eudaldgr** [comment]
Hint2: update the repo `git pull`, now checks only run under KISS Linux.

**Comment by aviumcaravan** [comment]
tysm for the patch
