### ISSUE TITLE
curl: not found & tinyramfs: not found [2]

### ISSUE THREAD

**Issue by spacedream** [eudaldgr/kiss-live#6]
Hello
as you probably not reading any more in my previous ticket (i wrote there more) cause you got it closed before i answered then i opening new one here, i hope you still can help. 
I think i found the root of my previous problem. Hopefully its will help you to help me. Here is the logfile (only last part of it):

[kiss-live.txt](https://github.com/eudaldgr/kiss-live/files/5521797/kiss-live.txt)

thank you again!

**Comment by spacedream** [comment]
just in case:
```
localhost ~ # df -h
Filesystem      Size  Used Avail Use% Mounted on
none            2.9G  892K  2.9G   1% /run
udev             10M     0   10M   0% /dev
tmpfs           2.9G  125M  2.8G   5% /dev/shm
/dev/sda3       137G  127G  3.0G  98% /
cgroup_root      10M     0   10M   0% /sys/fs/cgroup
keedsk          150M     0  150M   0% /mnt/keedsk
/dev/sdb1       440G  141G  277G  34% /home/xx/ut
tmpfs           590M   12K  590M   1% /run/user/1000
localhost ~ # df -h /tmp/
/dev/sda3       137G  127G  3.0G  98% /

```

if the reason of fail is not enough memory/space in /tmp folder.... well, it is possible to let script work only inside the folder its was run from and not go outside of it? its must be resolve my (and potentially others) problem. but its only if really problem in this, as i guess now, if script really needs more then 3Gb space on hdd. also i think its will be more "politically correct" too. off course you can just mount your own tmpfs for temporary work 'tmp' in any size you want. but inside the run (given) folder. please? thank you again, for your patience and help.

**Comment by eudaldgr** [comment]
I close this issue and lock conversation, because I haven't had time to answer the first one since you opened another one. Please redirect this on #5
