### ISSUE TITLE
Keyboard dead

### ISSUE THREAD

**Issue by ucodelukas** [eudaldgr/kiss-live#9]
Doesn't load the usb thingy or something

**Comment by ucodelukas** [comment]
Also missing firmware

**Comment by eudaldgr** [comment]
When doesn't load the usb keyboard? After bootloader or before?
Which firmware?
Can you test with the new release, please?
Thanks

**Comment by ucodelukas** [comment]
Sure

**Comment by eudaldgr** [comment]
Well, so you tried it?

**Comment by eudaldgr** [comment]
Closed due to inactivity.
